export { authApi, orgApi, chatApi, aiApi, contactsApi, calendarApi, wikiApi, mailApi, officeApi, automationApi, tasksApi } from './lib'
export type {
  Task,
  TaskStatus,
  TaskPriority,
  TaskSourceType,
  ListTasksFilters,
  ListTasksResponse,
  CreateTaskInput,
  UpdateTaskInput,
  DeleteTaskResponse,
  ProposedTask,
  ExtractTasksInput,
  ExtractTasksResponse,
} from './types/tasks'
export { api, API_BASE } from './lib/client'
export type { User, OrgSummary, AuthResponse, LoginResult, AcceptInvitationResponse } from './types'
export type {
  ArchiveContactResponse,
  ContactDirectoryItem,
  ContactStatus,
  ContactType,
  CreateContactInput,
  ListContactsResponse,
  UpdateContactInput,
} from './types'
export type {
  CalendarAttendee,
  CalendarItem,
  CalendarItemType,
  CalendarVisibility,
  CalendarTaskStatus,
  CreateCalendarItemInput,
  DeleteCalendarItemResponse,
  ListCalendarItemsInput,
  ListCalendarItemsResponse,
  UpdateCalendarItemInput,
} from './types/calendar'
export type {
  CreateWikiPageInput,
  DeleteWikiPageResponse,
  ListWikiPagesResponse,
  ListWikiSharesResponse,
  UpdateWikiPageInput,
  WikiAiEditProposedAction,
  WikiAiEditRequest,
  WikiAiEditResponse,
  WikiFavoriteResponse,
  WikiPage,
  WikiPageShare,
  WikiPageShareUser,
  WikiPageVisibility,
  WikiSharePermission,
} from './types/wiki'
export type {
  Department,
  Member,
  Invitation,
  WorkspaceRole,
  ListDepartmentsResponse,
  ListMembersResponse,
  ListInvitationsResponse,
  CreateInvitationResponse,
  CreateInvitationInput,
  CreateDepartmentInput,
} from './types/members'
export type {
  ChatConversationType,
  ChatAttachmentKind,
  ChatUser,
  ChatConversationMember,
  ChatAttachment,
  ChatReaction,
  ChatMessage,
  ChatConversation,
  ChatAttachmentDraft,
  CreateChannelInput,
  CreateDmInput,
  AddConversationMembersInput,
  CreateMessageInput,
  ListConversationAssetsInput,
  ListConversationsResponse,
  ListMessagesResponse,
  ListConversationAssetsResponse,
  CreateMessageResponse,
  ChatMessageResponse,
  DeleteMessageResponse,
  AddReactionResponse,
  CreateAttachmentUploadIntentInput,
  CreateAttachmentUploadIntentResponse,
  CompleteAttachmentUploadInput,
  CompleteAttachmentUploadResponse,
  ListPage,
  RealtimeEventTarget,
  ChatRealtimeEvent,
  ChatAssistMessage,
  ChatAiRequest,
  ChatAiResponse,
} from './types/chat'
export type {
  AiAuthContext,
  AiChatMessage,
  AiChatRequest,
  AiChatResponse,
  AiChatStreamEvent,
  AiFileAskRequest,
  AiFileAskResponse,
  AiFileIndexRequest,
  AiFileIndexResponse,
  AiFileMetadata,
  AiProposedAction,
  AiProposedActionType,
  AiRequestContext,
  AiSession,
  AiSessionMessage,
  AiSessionSummary,
  AiSource,
} from './types/ai'
export type {
  ForwardMailInput,
  ListMailAccountsResponse,
  ListMailThreadsInput,
  ListMailThreadsResponse,
  MailAccount,
  MailAccountStatus,
  MailActionResponse,
  MailAttachment,
  MailConnectResponse,
  MailMessage,
  MailMessageDirection,
  MailThread,
  MailThreadDetail,
  ReplyMailInput,
  SendMailInput,
} from './types/mail'
export type {
  OfficeRoom,
  OfficeRoomType,
  OfficeParticipant,
  MeetingNote,
  MeetingNotesSummary,
  MeetingTranscriptSegment,
  SummarizeMeetingNoteResponse,
  TranscribeMeetingRecordingInput,
  TranscribeMeetingRecordingResponse,
  LiveTranscriptionStatus,
  GenerateLiveKitTokenResponse,
  CreateRoomInput,
  UpdateRoomInput,
} from './types/office'
export type {
  AutomationRule,
  AutomationTriggerType,
  AutomationActionType,
  CreateAutomationRuleInput,
  UpdateAutomationRuleInput,
  ListAutomationRulesResponse,
} from './types/automation'
