export { authApi, orgApi, chatApi, contactsApi, calendarApi } from './lib'
export { api, API_BASE } from './lib/client'
export type { User, OrgSummary, AuthResponse, LoginResult, AcceptInvitationResponse } from './types'
export type {
  ArchiveContactResponse,
  ContactDirectoryItem,
  ContactStatus,
  ContactType,
  CreateContactInput,
  ListContactsResponse,
  UpdateContactInput,
} from './types'
export type {
  CalendarAttendee,
  CalendarItem,
  CalendarItemType,
  CalendarVisibility,
  CalendarTaskStatus,
  CreateCalendarItemInput,
  DeleteCalendarItemResponse,
  ListCalendarItemsInput,
  ListCalendarItemsResponse,
  UpdateCalendarItemInput,
} from './types/calendar'
export type {
  Department,
  Member,
  Invitation,
  WorkspaceRole,
  ListDepartmentsResponse,
  ListMembersResponse,
  ListInvitationsResponse,
  CreateInvitationResponse,
  CreateInvitationInput,
  CreateDepartmentInput,
} from './types/members'
export type {
  ChatConversationType,
  ChatAttachmentKind,
  ChatUser,
  ChatConversationMember,
  ChatAttachment,
  ChatReaction,
  ChatMessage,
  ChatConversation,
  ChatAttachmentDraft,
  CreateChannelInput,
  CreateDmInput,
  AddConversationMembersInput,
  CreateMessageInput,
  ListConversationAssetsInput,
  ListConversationsResponse,
  ListMessagesResponse,
  ListConversationAssetsResponse,
  CreateMessageResponse,
  ChatMessageResponse,
  DeleteMessageResponse,
  AddReactionResponse,
  CreateAttachmentUploadIntentInput,
  CreateAttachmentUploadIntentResponse,
  CompleteAttachmentUploadInput,
  CompleteAttachmentUploadResponse,
  ListPage,
  RealtimeEventTarget,
  ChatRealtimeEvent,
} from './types/chat'
